### ISSUE TITLE
Hey! Thats not an issue, but that's the only way i can contact you

### ISSUE THREAD

**Issue by satyr-bravo** [NAHDI51/cbz_to_pdf_converter#1]
I've stumbled upon your project, because i was in search of such utility. I happened to write something pretty similar before: 
https://github.com/Cydonyan/Manga2Djvu However, my script also sucks very much, so maybe we could join forces to develop an adequate tool for the job?

**Comment by NAHDI51** [comment]
Of course we can. However, this isn't much of a big project, one afternoon and I can probably write it out if I get the time, and some more to refurbish and complete. Maybe I will add some command based utility later on. I'd be very glad, however, if you can specify how you want to contribute
